### ISSUE TITLE
关于安装此插件依赖时发生的错误，以及运行时插件的导入失败

### ISSUE THREAD

**Issue by Smurf-Yvan** [ayakasuki/nonebot_plugin_mystool#2]
如下图所示，请指点
![图片](https://github.com/ayakasuki/nonebot_plugin_mystool/assets/128964123/6dcf2153-58b1-4029-bddb-8c8a872165d8)
![图片](https://github.com/ayakasuki/nonebot_plugin_mystool/assets/128964123/17ae866d-a4ff-44af-abeb-61b2404013e7)

**Comment by SuLiuming** [comment]
缺ntplib依赖
你可以在终端中运行以下命令使用 pip 安装 ntplib 模块：
pip install ntplib
如果你使用 Poetry 管理依赖项，可以在项目目录中运行以下命令：
poetry add ntplib

**Comment by Smurf-Yvan** [comment]
行，我先试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月19日(星期三) 上午9:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ayakasuki/nonebot_plugin_mystool] 关于安装此插件依赖时发生的错误，以及运行时插件的导入失败 (Issue #2)





 
缺ntplib依赖
 你可以在终端中运行以下命令使用 pip 安装 ntplib 模块：
 pip install ntplib
 如果你使用 Poetry 管理依赖项，可以在项目目录中运行以下命令：
 poetry add ntplib
